# Generated by Django 5.2.1 on 2025-06-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='code_files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(default='python', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('file_path', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('format', models.CharField(default='md', max_length=10)),
                ('code_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='core.codefile')),
            ],
        ),
    ]
