# Generated by Django 5.2.3 on 2025-06-16 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codefile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='documentation',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AddField(
            model_name='codefile',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentation',
            name='generation_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='file',
            field=models.FileField(upload_to='code_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py', 'js', 'jsx', 'ts', 'tsx', 'java', 'c', 'cpp', 'cs', 'php', 'rb', 'go', 'rs', 'swift', 'kt', 'scala', 'r', 'm', 'sh', 'sql', 'html', 'css', 'json', 'xml', 'yaml', 'yml', 'md', 'zip'])]),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='language',
            field=models.CharField(db_index=True, default='python', max_length=50),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='format',
            field=models.CharField(choices=[('md', 'Markdown'), ('html', 'HTML'), ('txt', 'Plain Text'), ('rtf', 'Rich Text Format'), ('pdf', 'PDF')], db_index=True, default='md', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['language', 'uploaded_at'], name='core_codefi_languag_207c89_idx'),
        ),
        migrations.AddIndex(
            model_name='codefile',
            index=models.Index(fields=['title', 'language'], name='core_codefi_title_955cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['code_file', 'format'], name='core_docume_code_fi_bbffac_idx'),
        ),
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['generated_at', 'format'], name='core_docume_generat_cb0fa8_idx'),
        ),
    ]
