# Generated by Django 4.2.23 on 2025-06-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enhanced_models_with_indexes'),
    ]

    operations = [
    ]
