# Generated by Django 4.2.23 on 2025-06-23 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_enhanced_models_with_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='owner',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='documentations', 
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name='documentation',
            index=models.Index(fields=['owner', 'generated_at'], name='core_docume_owner_id_c72e71_idx'),
        ),
    ]
