# Generated by Django 4.2.23 on 2025-06-23 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fix_index_migration'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentation',
            name='core_docume_owner_id_c72e71_idx',
        ),
    ]
