# Generated by Django 5.2.3 on 2025-06-24 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_remove_documentation_core_docume_owner_id_c72e71_idx'),
    ]

    operations = [
        # Recreate the table with correct constraints
        migrations.RunSQL(
            """
            CREATE TABLE "core_documentation_new" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, 
                "content" text NOT NULL, 
                "file_path" varchar(255) NOT NULL, 
                "generated_at" datetime NOT NULL, 
                "format" varchar(10) NOT NULL, 
                "code_file_id" bigint NOT NULL REFERENCES "core_codefile" ("id") DEFERRABLE INITIALLY DEFERRED, 
                "generation_time" real NOT NULL, 
                "owner_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            """,
            reverse_sql="DROP TABLE core_documentation_new;"
        ),
        migrations.RunSQL(
            """
            INSERT INTO core_documentation_new (id, content, file_path, generated_at, format, code_file_id, generation_time, owner_id)
            SELECT id, content, file_path, generated_at, format, code_file_id, generation_time, NULL FROM core_documentation;
            """,
            reverse_sql=""
        ),
        migrations.RunSQL(
            "DROP TABLE core_documentation;",
            reverse_sql=""
        ),
        migrations.RunSQL(
            "ALTER TABLE core_documentation_new RENAME TO core_documentation;",
            reverse_sql=""
        ),
    ]
