# Generated by Django 4.2.23 on 2025-06-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_ensure_userprofiles'),
        ('authentication', '0002_twofactorauth_userprofile_delete_usertwofactorauth'),
    ]

    operations = [
    ]
