# Generated by Django 4.2.23 on 2025-06-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_twofactor_is_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
